// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Run once (after `firebase login`):
/// ```bash
/// dart pub global activate flutterfire_cli
/// flutterfire configure --project=khata-manager-ccf3a
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB16lMUpmqMRWgT5oDEBtRrXD_--tfSMII',
    appId: '1:52181044796:web:08f928b369cbdbab447d39',
    messagingSenderId: '52181044796',
    projectId: 'khata-manager-ccf3a',
    authDomain: 'khata-manager-ccf3a.firebaseapp.com',
    databaseURL: 'https://khata-manager-ccf3a-default-rtdb.firebaseio.com',
    storageBucket: 'khata-manager-ccf3a.firebasestorage.app',
    measurementId: 'G-WC67238HVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'khata-manager-ccf3a',
    storageBucket: 'khata-manager-ccf3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'khata-manager-ccf3a',
    storageBucket: 'khata-manager-ccf3a.firebasestorage.app',
    iosBundleId: 'com.smartkhata.smartKhataManager',
  );
}